version: "3.3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.15.7
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # DataBase ENV
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=321
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 222:22
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_USER=gitea
      - MYSQL_DATABASE=gitea
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_PASSWORD=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
